export const SET_POKEMONS = "SET_POKEMONS";
export const SET_TYPES = "SET_TYPES";
export const SORT_BY_ORDER = "SORT_BY_ORDER";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_POKEMONS_PER_PAGE = "SET_POKEMONS_PER_PAGE";
export const SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
export const CREAR_POKEMON = "CREAR_POKEMON";
export const CREAR_POKEMON_REQUEST = 'CREAR_POKEMON_REQUEST';
export const CREAR_POKEMON_SUCCESS = 'CREAR_POKEMON_SUCCESS';
export const CREAR_POKEMON_FAILURE = 'CREAR_POKEMON_FAILURE';
export const RESET_FILTERS = "RESET_FILTERS";

